ParentingForLifelongHealth/plh-facilitator-app-mx-content

config.ts

Updated version number in order to fix android release action

updated version number

---

app_data/sheets/data_list/article_data.json

content: 1.1.12

---

app_data/sheets/contents.json
app_data/sheets/data_list/article_data.json
app_data/sheets/template/generated/article_faq_h_self_harm.json
config.ts

- add `faq_h_self_harm` article

content: 1.1.13

---

config.ts

@esmeetewinkel updated config for error logging

Added error logs

---

app_data/sheets/template/data_collection.json
config.ts

Make whatsapp forms available for Mexico

content: 1.1.17

---

app_data/sheets/data_list/generated/article_data.json
app_data/sheets/data_list/test_data.json
app_data/sheets/global/deployment_global_mx.json
app_data/sheets/template/test_template.json
config.ts

Replace references to supervisor_name by global

content: 1.1.19

---

app_data/sheets/contents.json
app_data/sheets/data_list/state.json
app_data/sheets/global/saf_resource_baja_california.json
app_data/sheets/global/saf_resource_chihuahua.json
app_data/sheets/global/saf_resource_mexico_city.json
app_data/sheets/global/saf_resource_michoacan.json
app_data/sheets/global/safeguard_resource.json
config.ts

Include functionality for dynamic global `@global.safeguard_resource`
[screen-capture (91).webm](https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74557272/73adcb1b-7224-46ba-b018-5507492bef7d)
Pending populating the sheets in [here](https://docs.google.com/spreadsheets/d/1JOBfFWK5NnSOlsSmN7JlI5o3cA-216ig2gH_AZmIhAI/edit#gid=576010168) with the actual phone numbers / contact details.

content: 1.1.22

---

app_data/sheets/data_list/article_data.json
config.ts

updated articles section if in draft

sync content from google sheets

---

.github/workflows/Translations down.yml

Creating an automated way to update translations

Create Translations down.yml

---

app_data/sheets/data_list/generated/article_data.json
app_data/sheets/data_list/report_data.json
app_data/sheets/data_list/state.json
app_data/sheets/template/parent_profile.json
app_data/translations/mx_es/strings.json
app_data/translations_source/translated_strings/translated.mx_es.json
config.ts

- Remove `exclude_from_translation` label on display group which caused `Co-parenting with` string not to be translated. (closes #45)
- Expand list of states to include 32 states, grouped into regions (progress towards #46)
- Content sync ahead of Crowdin update

content: 1.1.30

---

app_data/sheets/global/deployment_global.json
app_data/sheets/global/profile_global.json
config.ts

Content sync to include additional strings needed for #46

content: 1.1.31

---

app_data/sheets/template/profile_id.json
app_data/translations/mx_es/strings.json
app_data/translations_source/translated_strings/translated.mx_es.json
config.ts

Fix bug where Facilitator ID title and help pop-up were broken (because "id" was translated)
Before:
After:

content: 1.1.33

---

config.ts

- Update config so that this is a child deployment of FacilitatorApp
- As a consequence, the header is now compact and colourless

content: 1.1.35

---

app_data/assets/contents.json
app_data/sheets/data_list/profile_section_data.json
app_data/sheets/global/deployment_global.json
app_data/sheets/global/deployment_global_mx.json
app_data/sheets/template/media.json
config.ts

- first content sync after making this an extended deployment of `plh_facilitator`
- fix bug that parent groups don't appear 
- update iOS config

content: 1.1.36

---

app_data/sheets/template/parent_profile.json
config.ts

- Translation fix (two sentences were excluded from translation by mistake)
- Include Formando Conciencia+ theme and set as default (closes https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/issues/53)
Before / After:  
(Temporarily changed the code branch to `theme/plh_facilitator_mx`)

content: 1.1.38

---

app_data/sheets/contents.json
app_data/sheets/template/app_menu.json
app_data/sheets/template/import_user_data.json
app_data/sheets/template/message_box.json
config.ts

- Add theme button to dev side menu
- Add import user template to dev side menu
- Update `message_box` round share buttons to be theme orange
- Update theme so that yellow round button is pink

content: 1.1.41

---

app_data/sheets/template/import_user_data.json
config.ts

Fix user data retrieval template

content: 1.1.42

---

app_data/sheets/template/import_user_data.json
config.ts

Minor clarifications to Import user template (testing passed already web preview of v1.1.42) 
Screen recording on PR preview link: 
[Screenity video - Apr 5, 2024 (1).webm](https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/assets/74557272/4ea68a39-7abd-4752-97cd-28610fec9100)

content: 1.1.43

---

.github/workflows/deploy-pr-preview.yml

Updates path to code repo workflow following renaming from parenting-app-ui to open-app-builder

Update path to code repo workflow in deploy-pr-preview.yml

---

app_data/sheets/template/profile_id.json
config.ts

Provides a workaround for a bug whereby a user could see the profile ID page without having access to the value of their user ID.

content: 1.2.25

---

app_data/sheets/template/module_final.json
app_data/sheets/template/popup_nav.json
config.ts
reports/summary.json
reports/summary.md

content: 2.0.2

---

app_data/sheets/template/a_article_section.json
app_data/sheets/template/article_intro.json
app_data/sheets/template/article_message.json
app_data/sheets/template/article_related.json
app_data/sheets/template/menu/menu_task_flow_base.json
app_data/sheets/template/resource_element.json
config.ts
reports/summary.json
reports/summary.md

content: 2.0.5

---

app_data/assets/contents.json
app_data/sheets/contents.json
app_data/sheets/data_list/parents.json
app_data/sheets/generator/gen_module_final.json
app_data/sheets/template/add_report.json
app_data/sheets/template/article_loop.json
app_data/sheets/template/generated/final_before_chat.json
app_data/sheets/template/generated/final_day_3_mh_stress.json
app_data/sheets/template/generated/final_day_5_final_chat_session_5ux.json
app_data/sheets/template/generated/final_onboarding_day_chat.json
app_data/sheets/template/generated/final_week_1_chat.json
app_data/sheets/template/generated/final_week_2_chat.json
app_data/sheets/template/generated/final_week_3_chat.json
app_data/sheets/template/generated/final_week_4_chat.json
app_data/sheets/template/module_final.json
app_data/sheets/template/profile.json
app_data/sheets/template/profile_groups.json
app_data/sheets/template/report_card.json
app_data/sheets/template/reports.json
config.ts
reports/summary.json
reports/summary.md

Updated reports and sync'd css changes

content: 2.0.9

---

app_data/sheets/data_list/intro.json
app_data/sheets/data_list/modules.json
app_data/sheets/template/menu/menu_task_flow_base.json
app_data/sheets/template/menu_task_card.json
config.ts
reports/summary.json
reports/summary.md

updates #121
Fixes to content packages. Now filters depending on packages.
Updated main menu to remove progress as there is a possible issue to android phones during updating progress. This will mean once a module is completed the task card will not update. It will be added back in once issue is fixed.

content: 2.0.12

---

app_data/sheets/template/menu/menu_task_flow_base.json
app_data/sheets/template/menu_task_card.json
app_data/sheets/template/module_final.json
app_data/sheets/template/reports.json
config.ts
reports/summary.json
reports/summary.md

Fixes to reports.
Reports only show where report_id exists
after end of module will now go to existing report if exists

content: 2.0.14

---

app_data/sheets/template/add_coparent.json
app_data/sheets/template/parent_list.json
config.ts

updated co parent to not display in list

content: 2.0.16

---

app_data/sheets/template/article_message.json
app_data/sheets/template/message_element.json
config.ts
reports/summary.json
reports/summary.md

content: 2.0.17

---

app_data/sheets/template/article_message.json
app_data/sheets/template/menu/menu_task_flow_base.json
app_data/sheets/template/section_element.json
config.ts
reports/summary.json
reports/summary.md

updated sections to accordians

content: 2.0.18

---

app_data/sheets/template/resource_element.json
app_data/sheets/template/section_element.json
config.ts
reports/summary.json
reports/summary.md

content: 2.0.19

---

app_data/sheets/template/profile_about.json
config.ts
reports/summary.json
reports/summary.md

content: 2.0.24

---

app_data/sheets/template/pdf.json
config.ts
reports/summary.json
reports/summary.md

content: 2.0.25

---

app_data/sheets/template/add_coparent.json
app_data/sheets/template/parent_list.json
config.ts
reports/summary.json
reports/summary.md

Updated parents and co parent styling

content: 2.0.30

---

app_data/sheets/template/message_element.json
config.ts
reports/summary.json
reports/summary.md

updated share message for images

content: 2.0.31

---

app_data/assets/contents.json
app_data/sheets/contents.json
app_data/sheets/template/profile.json
config.ts
reports/summary.json
reports/summary.md

content: 2.0.32

---

app_data/sheets/template/add_report.json
app_data/sheets/template/article.json
app_data/sheets/template/library_article.json
app_data/sheets/template/message_element.json
config.ts
reports/summary.json
reports/summary.md

content: 2.0.36

---

app_data/assets/contents.json
app_data/sheets/contents.json
app_data/sheets/data_list/modules.json
app_data/sheets/data_list/pdf_data.json
app_data/sheets/template/library.json
app_data/sheets/template/menu/menu_task_flow.json
config.ts
reports/summary.json
reports/summary.md

fixes #113
Added guide to top of library although format is not correct yet

content: 2.0.44

---

app_data/assets/contents.json
app_data/sheets/data_list/lifecycle_actions/launch_actions.json
app_data/sheets/template/legal_terms/accept_terms.json
app_data/sheets/template/login.json
app_data/translations/mx_es/strings.json
app_data/translations_source/translated_strings/translated.mx_es.json
config.ts
reports/summary.json
reports/summary.md

- update login splash screen logic
- update translation of "Sign in with Google"

content: 2.1.20

---

app_data/sheets/template/add_group_button.json
app_data/sheets/template/add_in_person.json
app_data/sheets/template/add_parent.json
app_data/sheets/template/add_remote.json
app_data/sheets/template/edit_in_person.json
app_data/sheets/template/edit_parent_group.json
app_data/sheets/template/edit_remote.json
app_data/sheets/template/popup_nav.json
app_data/sheets/template/profile_groups.json
app_data/translations/mx_es/strings.json
app_data/translations_source/translated_strings/translated.mx_es.json
config.ts
reports/summary.json
reports/summary.md

-Add translation of "Create New Group"
- Add server sync action when finishing module, saving a report or adding a new parent group

content: 2.1.21

---

app_data/sheets/template/profile.json
app_data/sheets/template/profile_login.json
config.ts

Sheet changes (add force reload) to ensure "Sign in" / "Sign out" button text in Settings page updates immediately

content: 2.1.25
